name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8000:8000
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        working-directory: python-app/src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        working-directory: python-app/src
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: true

      #- name: Test with pytest
      #  working-directory: python-app/src
      #  run: |
      #    pip install pytest
      #    pytest

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: python-app/src
        run: docker build -t bruno74t/humangov-image:latest .

      - name: Push Backend Docker Image
        run: docker push bruno74t/humangov-image:latest

      - name: Run Docker container
        run: docker run -d -p 8000:8000 bruno74t/humangov-image:latest
